{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    alejandra
    audacity
    bash-completion
    bat
    brave
    chafa
    davinci-resolve
    deadnix
    dmidecode
    eza
    fd
    filezilla
    gcc
    gimp-with-plugins
    glib
    hunspell
    hunspellDicts.en-gb-large
    jq
    libreoffice-qt-fresh
    hyphenDicts.en-gb
    nil
    nix-bash-completions
    noisetorch
    nvtopPackages.nvidia
    openhue-cli
    pciutils
    pulseaudio
    ripgrep
    statix
    tree
    tailscale
    vlc
    wget
    wl-clipboard
  ];
}
